# Backstage override configuration for your local development environment
integrations:
  github:
    - host: github.com
      token: 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 # this should be the token from GitHub