apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: demo-template
  title: Golden Path - SpringBoot
  description: Create a simple microservice using Java, Maven, Springboot and GitHub Actions
  tags:
    - github-actions
    - java
    - recommended
  links:
    - title: Backstage
      url: https://backstage.io
      icon: backstage
    - title: Author
      url: https://github.com/kartiks123
      icon: github

spec:
  owner: kartiksengar1@gmail.com
  type: service

  parameters:
    - title: SpringBoot App
      required:
        - component_id
        - owner
        - java_package_name
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        java_package_name:
          title: Java Package Name
          type: string
          description: Name for the java package. eg (io.backstage.blah)
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

    - title: Docker Image
      required:
        - containerRegistry
        - imageName
        - imageProject
      properties:
        containerRegistry:
          title: Name
          type: string
          description: Unique name of the component
          enum:
            - DockerHub
            - ghcr.io
            - JFrog
            - AWS ECR
            - Google Container Registry
            - Azure Container Registry
        imageName:
          title: Docker Image Name
          type: string
          description: Name your Docker image - must be in lowercase
        imageProject:
          title: Docker Project
          type: string
          description: Project for collection of images - must be in lowercase

    - title: Let's create your Repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com
              - dev.azure.com
              - bitbucket.org
              - sample.gitonserver.net
            # requestUserCredentials:
            #   secretsKey: USER_OAUTH_TOKEN

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        # copyWithoutRender:
        #   - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          artifact_id: ${{ parameters.component_id }}
          java_package_name: ${{ parameters.java_package_name }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          http_port: 8080
          containerRegistry: ${{ parameters.containerRegistry }}
          imageName: ${{ parameters.imageName }}
          imageProject: ${{ parameters.imageProject }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public
        gitCommitMessage: "Scaffolder Magic"
        gitAuthorName: "kartiks123"
        gitAuthorEmail: "kartiksengar1@gmail.com"
        # token: ${{ secrets.USER_OAUTH_TOKEN }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
        icon: github
      - title: Open in catalog
        icon: backstage
        entityRef: ${{ steps.register.output.entityRef }}
